name: ds
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.16
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  shimmer: ^2.0.0
  connectivity_plus: ^3.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  fluro: ^2.0.4
  mask_text_input_formatter: ^2.4.0
  firebase_core: ^2.3.0
  provider: ^6.0.4
  flutter_linkify: ^5.0.2
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  clipboard: ^0.1.3
  curved_navigation_bar: ^1.0.3
  intl: ^0.17.0
  flutter_staggered_animations: ^1.1.1
  equatable: ^2.0.5
  firebase_ui_firestore: ^1.1.1
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

#  assets:
#    - assets/icons/
