import 'package:ds/utils/def.dart';
import 'package:ds/utils/errors.dart';

import '../hints.dart';
import '../keys.dart';
import '../titles.dart';

Map<String, String> en = {
  keys.en: "English",
  t.settings: "Settings",
  t.teacher: "Teacher",
  t.science: "Science",
  h.fullname: "Full name...",
  h.why: "Why...",
  t.editSchoolPride: "Edit school pride",
  t.avatar: "Avatar",
  t.joinedTime: "Joined time",
  t.newSchoolPride: "New school pride",
  t.selectLan: "Select language",
  t.teachers: "Teachers",
  t.ourPride: "Our proud",
  t.director: "Director",
  t.school: "School",
  t.statute: "Statute",
  t.sciences: "Sciences",
  t.login: "Login",
  t.news: "News",
  t.language: "Language",
  t.english: "English",
  t.russian: "Russian",
  t.uzbek: "Uzbek",
  t.uzbekKrill: "Uzbek krill",
  t.token: "Token",
  t.next: "Next",
  def.unknownError: "Unknown Error",
  def.invalidValue: "Invalid value",
  t.loginAsDirector: "Login as director",
  t.logInAsTeacher: "Login as teacher",
  t.signUpAsDirector: "Sign up as director",
  t.signUpAsTeacher: "Sign up as teacher",
  t.signIn: "Sign in",
  t.signUp: "Sign up",
  h.schoolName: "School number...",
  h.password: "Password...",
  h.nick: "Nick...",
  h.name: "Name...",
  h.science: "Science...",
  t.system: "System",
  t.profile: "Profile",
  t.schoolBio: "School bio",
  t.callSchedule: "Call schedule",
  t.receptionTime: "Reception Time",
  t.structure: "Structure",
  t.schoolPosts: "School posts",
  h.des: "Description...",
  h.title: "Title...",
  t.addScience: "Add science",
  t.add: "Add",
  t.update: "Update",
  t.editScience: "Edit science",
  t.addStatute: "Add new statute",
  t.editStatute: "Edit statute",
  h.chapterName: "Chapter name",
  t.statutes: "Statutes",
  t.statuteChapters: "statuteChapters",
  t.addChapter: "Add new chapter",
  t.editChapter: "Edit chapter",
  h.statute: "Statute...",
  t.makePost: "Make a post",
  t.editPost: "Edit post",
  t.pickVideo: "Pick a video",
  t.pickImage: "Pick a image",
  t.images: "Images",
  t.statistics: "Statistics",
  t.location: "Location",
  t.tels: "Phone numbers",
  t.socialMedia: "Social media",
  t.bio: "Bio",
  h.bio: "Bio...",
  h.location: "Location...",
  h.phoneNumber: "Phone number...",
  h.value: "Value...",
  t.addSchedule: "Add call schedule",
  t.editSchedule: 'Edit call schedule',
  t.schedule: "Call schedule",
  t.startTime: "Start time",
  t.endTime: "End time",
  t.addReceptionTime: "Add reception time",
  t.editReceptionTime: "Edit reception time",
  t.mon: "Mon",
  t.monday: "Monday",
  t.tue: "Tue",
  t.tuesday: "Tuesday",
  t.wed: "Wed",
  t.wednesday: "Wednesday",
  t.thu: "Thu",
  t.thursday: "Thursday",
  t.fri: "Fri",
  t.friday: "Friday",
  t.sat: "Sat",
  t.saturday: "Saturday",
  t.sun: "Sun",
  t.sunday: "Sunday",
  t.days: "Days",
  t.des: "Description",
  t.fullname: "Full name",
  t.save: "Save",
  t.generateNewToken: "Generate new token",
  t.tokens: "Tokens",
  myErrors.selectDays: "Select days",
  myErrors.fillDes: "Fill description",
  myErrors.startTime: "Select start time",
  myErrors.endTime: "Select end time",
  myErrors.usedNick: "Nick is already used",
  myErrors.scienceRequired: "Science is required",
  myErrors.invalidNick: "Invalid nick",
  myErrors.weakPassword: "Weak password",
  myErrors.passwordRequired: "Password is required",
  myErrors.nickRequired: "Nick is required",
  myErrors.nameRequired: "Name is required",
  myErrors.wrongPassword: "Wrong password",
  myErrors.userNotFound: "User not found",
  // t.profile: "Profile",

  h.classGrade: "Class grade(8-A)...",
  h.classTeacher: "Class teacher...",
  t.addClass: "Add class",
  t.detailClass: "Class",
  h.teacher: "Teacher...",
  t.signOut: "Sign out",
  t.article: "Article",
  t.myPosts: "My posts",
  t.articles: "Articles",
  t.writeNewArticle: "Write new article",
  t.editArticle: "Edit article",
  t.myArticles: "My articles",
};
