import 'package:ds/utils/def.dart';

import '../errors.dart';
import '../hints.dart';
import '../keys.dart';
import '../titles.dart';

Map<String, String> krill = {
  keys.krill: "Крилл",
  t.teacher: "Ўқитувчи",
  t.science: "Фан",
  t.selectLan: "Тилни танланг",
  t.teachers: "Ўқитувчилар",
  t.ourPride: "Фахрларимиз!",
  t.director: "Директор",
  t.school: "Мактаб",
  t.statute: "Низом",
  t.settings: "Созламалар",
  t.sciences: "Фанлар",
  t.avatar: "Аватар",
  t.editSchoolPride: "Мактаб фахрини таҳрирлаш",
  t.newSchoolPride: "Янги мактаб фахри",
  t.joinedTime: "Қўшилган вақти",
  h.fullname: "Тўлиқ исми шарифи...",
  h.why: "Нима учун...",
  t.login: "Тизимга кириш",
  t.news: "Янгиликлар",
  t.english: "Инглиз",
  t.russian: "Рус",
  t.uzbek: "Ўзбек",
  t.language: "Тил",
  t.uzbekKrill: "Ўзбек крилл",
  t.token: "Токен",
  t.next: "Кейингиси",

  def.unknownError: "Номаълум хато",
  def.invalidValue: "Нотўғри қиймат",
  t.signUpAsDirector: "Директор сифатида рўйхатдан ўтиш",
  t.signUpAsTeacher: "Устоз сифатида рўйхатдан ўтиш",
  t.loginAsDirector: "Диреcтор сифатида тизимга кириш",
  t.logInAsTeacher: "Ўқитувчи сифатида тизимга кириш",
  t.signIn: "Тизимга кириш",
  t.signUp: "Рўйхатдан ўтиш",
  h.schoolName: "Мактаб рақами...",
  h.password: "Тизим пароли...",
  h.nick: "Ник...",
  h.name: "Исм...",
  h.science: "Фан...",
  t.system: "Тизим",
  t.profile: "Профил",
  t.schoolBio: "Мактаб биографияси",
  t.callSchedule: "Қўнғироқлар жадвали",
  t.receptionTime: "Қабул вақти",
  t.structure: "Таркибий тузилма",
  t.schoolPosts: "Мактаб постлари",
  h.des: "Тавсиф...",
  h.title: "Сарлавҳа...",
  t.addScience: "Янги фан қўшиш",
  t.add: "Қўшиш",
  t.update: "Янгилаш",
  t.editScience: "Фанни таҳрирлаш",
  t.addStatute: "Янги низом қўшиш",
  t.editStatute: "Низомни таҳрирлаш",
  h.chapterName: "Боб номи...",
  t.statutes: "Низомлар",
  t.statuteChapters: "Низом боблари",
  t.addChapter: "Янги боб қўшиш",
  t.editChapter: "Бобни таҳрирлаш",
  h.statute: "Низом...",
  t.makePost: "Постни чиқариш",
  t.editPost: "Постни таҳрирлаш",
  t.pickVideo: "Видео жойлаш",
  t.pickImage: "Расм жойлаш",
  t.images: "Расмлар",
  t.statistics: "Статистика",
  t.location: "Манзил",
  t.tels: "Телефон рақамлари",
  t.socialMedia: "Ижтимоий тармоқлар",
  t.bio: "Биография",
  h.bio: "Биография...",
  h.location: "Биография...",
  h.phoneNumber: "Телефон рақами...",
  h.value: "Қиймат...",
  t.addSchedule: "Қўнғироқлар жадвалини қўшиш",
  t.editSchedule: "Қўнғироқлар жадвалини таҳрирлаш",
  t.schedule: "Қўнғироқлар жадвали",
  t.startTime: "Бошланиш вақти",
  t.endTime: "Тугаш вақти",
  t.addReceptionTime: "Қабул вақти қўшиш",
  t.editReceptionTime: "Қабул вақти таҳрирлаш",
  t.mon: "Душ",
  t.monday: "Душанба",
  t.tue: "Сеш",
  t.tuesday: "Сешанба",
  t.wed: "Чор",
  t.wednesday: "Чоршанба",
  t.thu: "Пай",
  t.thursday: "Пайшанба",
  t.fri: "Жум",
  t.friday: "Жума",
  t.sat: "Шан",
  t.saturday: "Шанба",
  t.sun: "Як",
  t.sunday: "Якшанба",
  t.days: "Кунлар",
  t.des: "Тавсиф",
  t.fullname: "Тўлиқ исм шариф",
  t.save: "Сақлаш",
  t.generateNewToken: "Янги токен генерация қилиш",
  t.tokens: "Токенлар",
  myErrors.selectDays: "Кунларни танланг",
  myErrors.fillDes: "Тавфис ни тўлдиринг",
  myErrors.startTime: "Бошланиш вақтини танланг",
  myErrors.endTime: "Тугаш вақтини танланг",
  myErrors.usedNick: "Ник аллақачон ишлатилган",
  myErrors.scienceRequired: "Фанни киритиш мажбурий",
  myErrors.weakPassword: "Парол кучсиз",
  myErrors.passwordRequired: "Паролни киритиш мажбурий",
  myErrors.nickRequired: "Ник ни киритиш мажбурий",
  myErrors.nameRequired: "Исмни киритиш мажбурий",
  myErrors.invalidNick: "Нотўғри ниcк",
  myErrors.wrongPassword: "Хато парол",
  myErrors.userNotFound: "Фойдаланувчи топилмади",

  // t.profile: "Profil",
};