import 'package:ds/utils/def.dart';
import 'package:ds/utils/errors.dart';

import '../hints.dart';
import '../keys.dart';
import '../titles.dart';


Map<String, String> ru = {
  keys.ru: "Русский",
  t.settings: "Настройки",
  t.teacher: "Учитель",
  t.science: "Наука",
  h.fullname:"ФИО...",
  h.why: "Почему...",
  t.editSchoolPride: "Изменить школьную гордость",
  t.avatar: "Аватар",
  t.joinedTime: "Время подключения",
  t.newSchoolPride: "Новая школьная гордость",
  t.selectLan: "Выбрать язык",
  t.teachers: "Учителя",
  t.ourPride: "Наша гордость",
  t.director: "Директор",
  t.school: "Школа",
  t.statute: "Статут",
  t.sciences: "наук",
  t.login: "Авторизоваться",
  t.news: "Новости",
  t.language: "Язык",
  t.english: "Английский",
  t.russian: "Русский",
  t.uzbek: "Узбекский",
  t.uzbekKrill: "Узбекский криль",
  t.token: "Токен",
  t.next: "Следующий",
  def.unknownError: "Неизвестная ошибка",
  def.invalidValue: "Неверное значение",
  t.loginAsDirector: "Войти как директор",
  t.logInAsTeacher: "Войти как учитель",
  t.signUpAsDirector: "Зарегистрироваться как директор",
  t.signUpAsTeacher: "Зарегистрироваться как учитель",
  t.signIn: "Войти",
  t.signUp: "Зарегистрироваться",
  h.schoolName: "Номер школы...",
  h.password: "Пароль...",
  h.nick: "Ник...",
  h.name: "Имя...",
  h.science: "Наука...",
  t.system: "Система",
  t.profile: "Профиль",
  t.schoolBio: "биография школы",
  t.callSchedule: "Расписание звонков",
  t.receptionTime: "Время приема",
  t.structure: "Состав",
  t.schoolPosts: "Школьные посты",
  h.des: "Описание...",
  h.title: "Заголовок...",
  t.addScience: "Добавить науку",
  t.add: "Добавлять",
  t.update: "Обновлять",
  t.editScience: "Изменить науку",
  t.addStatute: "Добавить новый устав",
  t.editStatute: "Изменить устав",
  h.chapterName: "Название главы",
  t.statutes: "Устав",
  t.statuteChapters: "Главы устава",
  t.addChapter: "Добавить новую главу",
  t.editChapter: "Изменить главу",
  h.statute: "Статут...",
  t.makePost: "Сделать пост",
  t.editPost: "Редактировать сообщение",
  t.pickVideo: "Выберите видео",
  t.pickImage: "Выберите изображение",
  t.images: "Картинки",
  t.statistics: "Статистика",
  t.location: "Место нахождения",
  t.tels: "Телефонные номера",
  t.socialMedia: "Социальные медиа",
  t.bio: "Био",
  h.bio: "Био...",
  h.location: "Место нахождения...",
  h.phoneNumber: "Номер телефона...",
  h.value: "Ценить...",
  t.addSchedule: "Добавить расписание звонков",
  t.editSchedule: 'Изменить расписание звонков',
  t.schedule: "Расписание звонков",
  t.startTime: "Время начала",
  t.endTime: "Время окончания",
  t.addReceptionTime: "Добавить время приема",
  t.editReceptionTime: "Изменить время приема",
  t.mon: "пн",
  t.monday: "Понедельник",
  t.tue: "вт",
  t.tuesday: "Вторник",
  t.wed: "ср",
  t.wednesday: "Среда",
  t.thu: "чт",
  t.thursday: "Четверг",
  t.fri: "пт",
  t.friday: "Пятница",
  t.sat: "сб",
  t.saturday: "Суббота",
  t.sun: "вс",
  t.sunday: "Воскресенье",
  t.days: "Дни",
  t.des: "Описание",
  t.fullname: "ФИО",
  t.save: "Сохранить",
  t.generateNewToken: "Создать новый токен",
  t.tokens: "Токены",
  myErrors.selectDays: "Выберите дни",
  myErrors.fillDes: "Заполнить описание",
  myErrors.startTime: "Выберите время начала",
  myErrors.endTime: "Выберите время окончания",
  myErrors.usedNick: "Ник уже используется",
  myErrors.scienceRequired: "Требуется наука",
  myErrors.invalidNick: "Неверный ник",
  myErrors.weakPassword: "слабый пароль",
  myErrors.passwordRequired: "Необходим пароль",
  myErrors.nickRequired: "Ник обязателен",
  myErrors.nameRequired: "Укажите имя",
  myErrors.wrongPassword: "Неправильный пароль",
  myErrors.userNotFound: "Пользователь не найден",
  // t.profile: "Profile",
};
