import 'package:ds/utils/def.dart';

import '../errors.dart';
import '../hints.dart';
import '../keys.dart';
import '../titles.dart';

Map<String, String> uz = {
  keys.uz: "O'zbek",
  t.teacher: "O'qituvchi",
  t.science: "Fan",
  t.selectLan: "Tilni tanlang",
  t.teachers: "O'qituvchilar",
  t.ourPride: "Faxrlarimiz!",
  t.director: "Direktor",
  t.school: "Maktab",
  t.statute: "Nizom",
  t.settings: "Sozlamalar",
  t.sciences: "Fanlar",
  t.avatar: "Avatar",
  t.editSchoolPride: "Maktab faxrini tahrirlash",
  t.newSchoolPride: "Yangi maktab faxri",
  t.joinedTime: "Qo'shilgan vaqti",
  h.fullname: "To'liq ismi sharifi...",
  h.why: "Nima uchun...",
  t.login: "Tizimga kirish",
  t.news: "Yangiliklar",
  t.english: "Ingliz",
  t.russian: "Rus",
  t.uzbek: "O'zbek",
  t.language: "Til",
  t.uzbekKrill: "O'zbek krill",
  t.token: "Token",
  t.next: "Keyingisi",

  def.unknownError: "Noma'lum xato",
  def.invalidValue: "Noto'g'ri qiymat",
  t.signUpAsDirector: "Direktor sifatida ro'yxatdan o'tish",
  t.signUpAsTeacher: "Ustoz sifatida ro'yxatdan o'tish",
  t.loginAsDirector: "Director sifatida tizimga kirish",
  t.logInAsTeacher: "O'qituvchi sifatida tizimga kirish",
  t.signIn: "Tizimga kirish",
  t.signUp: "Ro'yxatdan o'tish",
  h.schoolName: "Maktab raqami...",
  h.password: "Tizim paroli...",
  h.nick: "Nick...",
  h.name: "Ism...",
  h.science: "Fan...",
  t.system: "Tizim",
  t.profile: "Profil",
  t.schoolBio: "Maktab biografiyasi",
  t.callSchedule: "Qo'ng'iroqlar jadvali",
  t.receptionTime: "Qabul vaqti",
  t.structure: "Tarkibiy tuzilma",
  t.schoolPosts: "Maktab postlari",
  h.des: "Tavsif...",
  h.title: "Sarlavha...",
  t.addScience: "Yangi fan qo'shish",
  t.add: "Qo'shish",
  t.update: "Yangilash",
  t.editScience: "Fanni tahrirlash",
  t.addStatute: "Yangi nizom qo'shish",
  t.editStatute: "Nizomni tahrirlash",
  h.chapterName: "Bob nomi...",
  t.statutes: "Nizomlar",
  t.statuteChapters: "Nizom boblari",
  t.addChapter: "Yangi bob qo'shish",
  t.editChapter: "Bobni tahrirlash",
  h.statute: "Nizom...",
  t.makePost: "Postni chiqarish",
  t.editPost: "Postni tahrirlash",
  t.pickVideo: "Video joylash",
  t.pickImage: "Rasm joylash",
  t.images: "Rasmlar",
  t.statistics: "Statistika",
  t.location: "Manzil",
  t.tels: "Telefon raqamlari",
  t.socialMedia: "Ijtimoiy tarmoqlar",
  t.bio: "Biografiya",
  h.bio: "Biografiya...",
  h.location: "Manzil...",
  h.phoneNumber: "Telefon raqami...",
  h.value: "Qiymat...",
  t.addSchedule: "Qo'ng'iroqlar jadvalini qo'shish",
  t.editSchedule: "Qo'ng'iroqlar jadvalini tahrirlash",
  t.schedule: "Qo'ng'iroqlar jadvali",
  t.startTime: "Boshlanish vaqti",
  t.endTime: "Tugash vaqti",
  t.addReceptionTime: "Qabul vaqti qo'shish",
  t.editReceptionTime: "Qabul vaqti tahrirlash",
  t.mon: "Dush",
  t.monday: "Dushanba",
  t.tue: "Sesh",
  t.tuesday: "Seshanba",
  t.wed: "Chor",
  t.wednesday: "Chorshanba",
  t.thu: "Pay",
  t.thursday: "Payshanba",
  t.fri: "Jum",
  t.friday: "Juma",
  t.sat: "Shan",
  t.saturday: "Shanba",
  t.sun: "Yak",
  t.sunday: "Yakshanba",
  t.days: "Kunlar",
  t.des: "Tavsif",
  t.fullname: "To'liq ism sharif",
  t.save: "Saqlash",
  t.generateNewToken: "Yangi token generatsiya qilish",
  t.tokens: "Tokenlar",
  myErrors.selectDays: "Kunlarni tanlang",
  myErrors.fillDes: "Tavfis ni to'ldiring",
  myErrors.startTime: "Boshlanish vaqtini tanlang",
  myErrors.endTime: "Tugash vaqtini tanlang",
  myErrors.usedNick: "Nick allaqachon ishlatilgan",
  myErrors.scienceRequired: "Fanni kiritish majburiy",
  myErrors.weakPassword: "Parol kuchsiz",
  myErrors.passwordRequired: "Parolni kiritish majburiy",
  myErrors.nickRequired: "Nick ni kiritish majburiy",
  myErrors.nameRequired: "Ismni kiritish majburiy",
  myErrors.invalidNick: "Noto'g'ri nick",
  myErrors.wrongPassword: "Xato parol",
  myErrors.userNotFound: "Foydalanuvchi topilmadi",
  // t.profile: "Profil",

  h.classGrade: "Sinf darajasi(8-A)...",
  h.classTeacher: "Sinf ustozi...",
  t.addClass: "Sinf qo'shish",
  t.detailClass: "Sinf",
  t.teacher: "Ustoz...",
  t.signOut: "Tizimdan chiqish",
  t.article: "Maqola",
  t.myPosts: "Mening postlarim",
  t.articles: "Maqolalar",
  t.writeNewArticle: "Yangi maqola yozish",
  t.editArticle: "Maqolani tahrirlash",
  t.myArticles: "Mening maqolalarim",
};
