// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTWVBK9OZvcyRJJ0M7i8IkQ35krKpPFI',
    appId: '1:460062178607:web:dcfcba0e5ce3ab1831f5da',
    messagingSenderId: '460062178607',
    projectId: 'digitalization-of-school',
    authDomain: 'digitalization-of-school.firebaseapp.com',
    storageBucket: 'digitalization-of-school.appspot.com',
    measurementId: 'G-80C0RZH4TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNF1lCfKbBJZTFNZhvXdrU9q-eO5ugKtQ',
    appId: '1:460062178607:android:629e0726ffab08a431f5da',
    messagingSenderId: '460062178607',
    projectId: 'digitalization-of-school',
    storageBucket: 'digitalization-of-school.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpxEuwBiiMZr3PLDTLW6OUo32zU4VzdE',
    appId: '1:460062178607:ios:5ed789775c29956a31f5da',
    messagingSenderId: '460062178607',
    projectId: 'digitalization-of-school',
    storageBucket: 'digitalization-of-school.appspot.com',
    iosClientId: '460062178607-82mkd5luq8jqg87ligruaqoqleuq66t7.apps.googleusercontent.com',
    iosBundleId: 'com.ds.ds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpxEuwBiiMZr3PLDTLW6OUo32zU4VzdE',
    appId: '1:460062178607:ios:5ed789775c29956a31f5da',
    messagingSenderId: '460062178607',
    projectId: 'digitalization-of-school',
    storageBucket: 'digitalization-of-school.appspot.com',
    iosClientId: '460062178607-82mkd5luq8jqg87ligruaqoqleuq66t7.apps.googleusercontent.com',
    iosBundleId: 'com.ds.ds',
  );
}
